### ISSUE TITLE
Undo stack loses info after undo followed by new insertion

### ISSUE THREAD

**Issue by andrewheumann** [yjs/y-utility#4]
**Checklist**

* [X] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [X] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
After a sequence where we:
- add some changes
- undo a single change 
- add another individual change
we are no longer able to undo back past the previous undo. 

**To Reproduce**
Here is a test which demonstrates the issue:

```js
/**
 * @param {t.TestCase} tc
 */
export const testUndoAfterChangeAfterUndo = tc => {
  const um = new YMultiDocUndoManager()
  const ydoc1 = new Y.Doc()
  const ytype1 = ydoc1.getText()
  um.addToScope([ytype1])

  ytype1.insert(0, 'a')

  t.assert(ytype1.toString() === 'a')
  t.assert(um.undoStack.length === 1)

  ytype1.insert(1, 'b')

  t.assert(ytype1.toString() === 'ab')
  t.assert(um.undoStack.length === 2)

  ytype1.insert(2, 'c')

  t.assert(ytype1.toString() === 'abc')
  t.assert(um.undoStack.length === 3)

  um.undo()

  t.assert(ytype1.toString() === 'ab')
  t.assert(um.undoStack.length === 2)

  ytype1.insert(2, 'x')

  t.assert(ytype1.toString() === 'abx')
  t.assert(um.undoStack.length === 3) // This is 1, instead of 3

  um.undo()

  t.assert(ytype1.toString() === 'ab')
  t.assert(um.undoStack.length === 2)

  um.undo() // this undo would be unavailable

  t.assert(ytype1.toString() === 'a')
  t.assert(um.undoStack.length === 1)
}
```

**Expected behavior**
I expect to be able to continue to undo back through the entire stack after a change that follows an undo.

**Screenshots**
**Environment Information**
 - NodeJS v16, building this repository from source
 - Yjs version 13.5.29

**Comment by andrewheumann** [comment]
Also worth noting that if I swap out the `YMultiDocUndoManager` for a `Y.UndoManager` in the test, it passes.

**Comment by andrewheumann** [comment]
FWIW this change seems to cause the test to pass, but I confess I'm groping around in the dark a bit here, not sure it's a valid solution:

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/31935763/228570579-4b39399b-c6ed-4739-94ce-2e71b7c17063.png">

**Comment by andrewheumann** [comment]
Thank you for fixing this so quickly! much appreciated!

**Comment by dmonad** [comment]
Sure thing. Thanks for the test case and the correct fix! I incorporated both in the fix :-)
